### ISSUE TITLE
[image gzip issue] With default settings, images are not being gzipped by default

### ISSUE THREAD

**Issue by ethereal-sandeep** [sbt/sbt-gzip#9]
I observed a weird behaviour while using this plugin. My settings are as mentioned in documentation with the following pipeline config
`pipelineStages` := Seq(imagemin, digest, gzip)`

when includeFilter is not overridden then all files except images are gzipped 

but when i  add this line in build.sbt
`includeFilter in gzip := "*.html" || "*.js" || "*.css" || "*.png" || "*.jpg" || "*.jpeg" || "*.svg"`

it is able to gzip image .

Why its not  gzipping images by default ? It should ideally include all the files in public asset right?

Also can this be used to gzip json response being generated by play framework? I am aware of the fact that json response are not generated as assets but when i use the `https://www.playframework.com/documentation/2.2.x/GzipEncoding` then it sort of end the use case of sbt-gzip. its little confusing...

**Comment by strelec** [comment]
Images should not be gzipped.

**Comment by jroper** [comment]
By default, only HTML, css and js is gzipped:

https://github.com/sbt/sbt-gzip/blob/master/src/main/scala/com/typesafe/sbt/gzip/SbtGzip.scala#L27

There's a good reason for not gzipping images - images are already stored in a compressed format, zipping them will generally not result in a smaller file size, and could even result in a larger file size. So the effect is that you're making the browser use more cpu (because it has to unzip them to display them) for no advantage whatsoever.

For example, go to my profile page, and download my profile image. It's 47955 bytes. If I gzip it, it ends up being 47836 bytes, only 119 bytes smaller, less than a single IP packet. gzipping it will save no network bandwidth, but will cause the clients cpu to do more work, which will mean the page will be slower to render (and mobile clients will have their batteries go flat faster). So it doesn't make sense to gzip it.

**Comment by ethereal-sandeep** [comment]
@jroper  Thanks for the clarification !
